//! Host-owned Agent launch transaction over Herdr Agent APIs.
//!
//! [INPUT]: a typed [`AgentLaunchIntent`] (the user's original prompt,
//! Project path, branch, mode/permissions, attachments), a Herdr adapter
//! implementing [`AgentLaunchRuntime`], and a [`ProjectPreparation`]
//! implementation.
//! [OUTPUT]: `run_agent_launch` / `run_agent_launch_with_ledger` — the single
//! regular Agent launch transaction: validate → branch/worktree preparation
//! → integration ensure (fire-and-log) → create runtime structures without
//! focus → `agent.start` (launch argv generated by Host policy) → typed
//! readiness verification → verified post-ready keys (Plan+PostLaunchKeys
//! only) → exactly one semantic initial prompt → exact Conversation binding
//! → exactly one deterministic task title; the ledger variant replays
//! stably to success or an `AgentCreated` result for the same operation id.
//! [POS]: plan M2 / audit AF-03. Normal launches no longer type into a PTY;
//! explicit terminal commands still go through the Terminal channel.
//! Terminal text/Enter is never the transport for Agent launch/prompt.

use crate::agent_integrations::ensure_provider;
use crate::agent_titles::suggest_task_title;
use crate::conversations::{agent_id_from_herdr_kind, continued_identity, herdr_agent_kind};
use crate::diagnostics::lag_log;
use crate::dto::ConversationIdentity;
use crate::herdr::{
    AgentPromptParams, AgentSendKeysParams, AgentStartParams, AgentStartedResult, AgentWaitParams,
    HerdrAgentStatus, HerdrClient, HerdrError, TabCreatedResult, WorkspaceCreatedResult,
};
use crate::ids::AgentRef;
use crate::provider_capabilities::{provider_plan_support, ProviderPlanSupport};
use shardlane_history::models::AgentId;
use std::fmt;
use std::path::{Path, PathBuf};
use std::time::Duration;

const SHELL_READY_TIMEOUT_MS: u64 = 10_000;
const AGENT_START_TIMEOUT_MS: u64 = 45_000;
const PROMPT_SUBMIT_TIMEOUT_MS: u64 = 20_000;
const READINESS_TIMEOUT_MS: u64 = 45_000;
/// Provider CLIs register their typed session asynchronously after the first
/// readiness signal (a cold `claude` boot can take several seconds to attach
/// `agent_session`). Verification retries inside this window before declaring
/// the launch `agent_created`.
const IDENTITY_VERIFY_TIMEOUT_MS: u64 = 20_000;
const IDENTITY_VERIFY_POLL_MS: u64 = 500;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AgentLaunchMode {
    Plan,
    Build,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AgentPermission {
    AskApproval,
    AutoApprove,
    FullAccess,
}

/// Semantic launch request. `prompt` is the user's original text (before any
/// launch-builder suffix); attachments are absolute paths resolved by the
/// client's reference picker.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AgentLaunchIntent {
    /// Stable semantic operation id. Transport adapters may generate one for
    /// legacy requests, but a Conversation/AgentRef is never a substitute.
    pub operation_id: String,
    /// Preferred runtime workspace for the new tab, when the client resolved one.
    pub workspace_id: Option<String>,
    pub project_path: String,
    pub branch: String,
    pub mode: AgentLaunchMode,
    pub permission: AgentPermission,
    pub agent: AgentId,
    pub prompt: String,
    pub attachments: Vec<PathBuf>,
    /// Extra provider argv ahead of the mode/permission flags — e.g. the exact
    /// native resume arguments for a History continuation.
    pub extra_args: Vec<String>,
    /// Launch without an initial prompt (History continuation with no
    /// instruction: bind the Conversation and open Chat instead of sending).
    pub skip_initial_prompt: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AgentLaunchFailure {
    ProjectUnavailable(String),
    BranchPreparationFailed(String),
    RuntimeCreateFailed(String),
    AgentStartFailed(String),
    /// The outcome of `agent.start` is uncertain (the response was never
    /// read) and it cannot be proven the target pane is held by the intended
    /// provider. The mutation is never retried; the tab is not reaped (a
    /// valid Agent may already live there).
    AgentStartUncertain {
        /// The tab/pane allocated before the response was lost. It remains
        /// owned by this logical operation and must be reconciled, never
        /// blindly launched again.
        agent_ref: crate::ids::AgentRef,
        tab_id: String,
        pane_id: String,
        detail: String,
    },
    AgentNotReady(String),
    /// The user-requested Plan mode could not be established (post-ready keys
    /// rejected). The Agent runs on in its default mode; the launch reports
    /// the mode-setup failure truthfully (AC-18).
    PlanSetupFailed(String),
    InitialPromptFailed(String),
    /// P0-04: the launch transaction already COMMITTED (`agent.start` was
    /// accepted; the Agent exists in its pane) and a later phase failed. The
    /// created structure is reported so callers reconcile instead of
    /// describing the whole transaction as "not started" and retrying into a
    /// duplicate Agent.
    AgentCreated {
        agent_ref: crate::ids::AgentRef,
        tab_id: String,
        pane_id: String,
        phase: CreatedAgentPhase,
        detail: String,
    },
    /// A logical launch id was already used for a different request shape.
    /// This is a caller error, not a runtime failure and must never execute a
    /// second `agent.start` mutation.
    OperationConflict(String),
}

/// Which post-commit phase of the launch failed (P0-04).
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CreatedAgentPhase {
    /// The `agent.start` response was not observed after the mutation write.
    /// The allocated target is preserved for explicit reconciliation.
    StartUncertain,
    /// Typed readiness/identity verification failed after start.
    NotReady,
    /// Plan-mode setup keys were rejected after start.
    PlanSetup,
    /// The initial semantic prompt was definitely rejected after start.
    InitialPrompt,
    /// The initial prompt's outcome is unknown — the Agent exists and may
    /// already have the instruction.
    InitialPromptUncertain,
    /// A post-commit projection (for example, pane layout) failed after the
    /// Agent and its initial instruction were already accepted.
    Projection,
}

impl fmt::Display for AgentLaunchFailure {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::ProjectUnavailable(message) => {
                write!(formatter, "project unavailable: {message}")
            }
            Self::BranchPreparationFailed(message) => {
                write!(formatter, "branch preparation failed: {message}")
            }
            Self::RuntimeCreateFailed(message) => {
                write!(formatter, "runtime creation failed: {message}")
            }
            Self::AgentStartFailed(message) => write!(formatter, "agent start failed: {message}"),
            Self::AgentStartUncertain {
                agent_ref,
                tab_id,
                pane_id: _,
                detail,
            } => write!(
                formatter,
                "agent start result uncertain for pane={} (tab={}; not retried; reconcile this target): {detail}",
                agent_ref.as_str(),
                tab_id
            ),
            Self::AgentNotReady(message) => write!(formatter, "agent not ready: {message}"),
            Self::PlanSetupFailed(message) => write!(
                formatter,
                "requested Plan mode could not be established: {message}"
            ),
            Self::InitialPromptFailed(message) => {
                write!(formatter, "initial prompt failed: {message}")
            }
            Self::AgentCreated {
                agent_ref,
                tab_id,
                pane_id: _,
                phase,
                detail,
            } => {
                let phase = match phase {
                    CreatedAgentPhase::StartUncertain => "agent start (delivery uncertain)",
                    CreatedAgentPhase::NotReady => "readiness verification",
                    CreatedAgentPhase::PlanSetup => "plan-mode setup",
                    CreatedAgentPhase::InitialPrompt => "initial prompt",
                    CreatedAgentPhase::InitialPromptUncertain => {
                        "initial prompt (delivery uncertain)"
                    }
                    CreatedAgentPhase::Projection => "post-launch projection",
                };
                write!(
                    formatter,
                    "agent already created (pane={}, tab={}) but {phase} failed: {detail}; the Agent is running — reconcile it instead of retrying the launch",
                    agent_ref.as_str(),
                    tab_id
                )
            }
            Self::OperationConflict(message) => write!(formatter, "launch operation conflict: {message}"),
        }
    }
}

impl std::error::Error for AgentLaunchFailure {}

/// Successful launch. `identity == None` is a degraded success: the runtime
/// Agent exists and works, but no semantic Conversation can be bound, so the
/// client presents the Terminal instead of Chat (never a launch failure).
#[derive(Clone, Debug)]
pub struct AgentLaunchOutcome {
    pub agent_ref: AgentRef,
    pub pane_id: String,
    pub tab_id: String,
    pub workspace_id: String,
    pub identity: Option<ConversationIdentity>,
    /// Title applied through the deterministic heuristic, when confidence was
    /// high; otherwise the provider display name was used.
    pub task_title: Option<String>,
    pub created: TabCreatedResult,
    pub layout: crate::herdr::PaneLayout,
}

/// Runtime seam for the launch transaction. The production implementation is
/// `HerdrClient`; tests implement a counting mock.
/// Settled status for handoff-after-turn: the current turn has ended (idle)
/// or is explicitly waiting for terminal input (blocked).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SettledStatus {
    Idle,
    Blocked,
}

pub trait AgentLaunchRuntime {
    type Error: fmt::Display;

    fn create_tab_without_focus(
        &self,
        workspace_id: Option<&str>,
        cwd: &str,
    ) -> Result<TabCreatedResult, Self::Error>;
    fn create_workspace_without_focus(
        &self,
        cwd: &str,
    ) -> Result<WorkspaceCreatedResult, Self::Error>;
    fn workspace_id_for_path(&self, project_path: &str) -> Result<Option<String>, Self::Error>;
    fn start_agent(&self, params: &AgentStartParams) -> Result<AgentStartedResult, Self::Error>;
    fn wait_agent_idle(&self, target: &str, timeout_ms: u64) -> Result<(), Self::Error>;
    /// Wait until the freshly created pane's shell is interactive so
    /// `agent.start` has a usable shell to hand the Agent to.
    fn wait_shell_ready(&self, pane_id: &str, timeout_ms: u64) -> Result<(), Self::Error>;
    /// Exact-target wait until the Agent's current turn has settled (idle or
    /// blocked). Used by live handoff; never a global watcher.
    fn wait_agent_settled(
        &self,
        target: &str,
        timeout_ms: u64,
    ) -> Result<SettledStatus, Self::Error>;
    fn agent_by_pane(&self, pane_id: &str) -> Result<Option<crate::herdr::Agent>, Self::Error>;
    /// Whether an error means "the request may have been accepted but the
    /// response was not read" (socket read timeout / server wait timeout).
    /// Uncertain mutations must never be repeated blindly (AC-01); they are
    /// reconciled instead. The default suits runtimes whose errors are always
    /// definitive.
    fn error_is_uncertain(&self, _error: &Self::Error) -> bool {
        false
    }
    fn prompt_agent_once(&self, target: &str, text: &str) -> Result<(), Self::Error>;
    fn send_agent_keys(&self, target: &str, keys: &[String]) -> Result<(), Self::Error>;
    fn rename_tab(&self, tab_id: &str, label: &str) -> Result<(), Self::Error>;
    fn rename_pane(&self, pane_id: &str, label: &str) -> Result<(), Self::Error>;
    fn close_tab(&self, tab_id: &str) -> Result<(), Self::Error>;
    fn pane_layout(&self, pane_id: &str) -> Result<crate::herdr::PaneLayout, Self::Error>;
}

/// Project/branch preparation seam. The production implementation reuses or
/// creates Git worktrees under a Shardlane-owned root.
pub trait ProjectPreparation {
    fn prepare(&self, project_path: &str, branch: &str) -> Result<PreparedProject, String>;
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PreparedProject {
    pub cwd: PathBuf,
    pub worktree_created: bool,
}

/// Provider startup argv derived from mode/permission. Claude/Gemini express
/// plan mode through CLI flags; Codex expresses permission through flags and
/// plan mode through post-ready keys; others get no flags (plan intent flows
/// through the prompt prefix instead).
pub fn agent_startup_args(
    agent: AgentId,
    mode: AgentLaunchMode,
    permission: AgentPermission,
) -> Vec<String> {
    match agent {
        AgentId::ClaudeCode => {
            let base_mode = match (mode, permission) {
                (AgentLaunchMode::Plan, _) => "plan",
                (_, AgentPermission::AskApproval) => "default",
                (_, AgentPermission::AutoApprove) => "acceptEdits",
                (_, AgentPermission::FullAccess) => "bypassPermissions",
            };
            vec!["--permission-mode".to_string(), base_mode.to_string()]
        }
        AgentId::Codex => match permission {
            AgentPermission::AskApproval => Vec::new(),
            // R2-13: AutoApprove is an approval-policy + sandbox-policy PAIR,
            // not a version-specific alias (`--full-auto` and
            // `--approve-for-me` are both rejected by different installed
            // Codex versions). `-s workspace-write -a never` is accepted by
            // every probed 0.142+ CLI: sandboxed execution, no approval
            // prompts — the product meaning of AutoApprove.
            AgentPermission::AutoApprove => vec![
                "--sandbox".to_string(),
                "workspace-write".to_string(),
                "--ask-for-approval".to_string(),
                "never".to_string(),
            ],
            AgentPermission::FullAccess => {
                vec!["--dangerously-bypass-approvals-and-sandbox".to_string()]
            }
        },
        AgentId::Gemini => {
            let approval_mode = match (mode, permission) {
                (AgentLaunchMode::Plan, _) => "plan",
                (_, AgentPermission::AskApproval) => "default",
                (_, AgentPermission::AutoApprove) | (_, AgentPermission::FullAccess) => "auto-edit",
            };
            vec![format!("--approval-mode={approval_mode}")]
        }
        _ => Vec::new(),
    }
}

/// R2-13: runtime-probe whether the INSTALLED Codex CLI accepts the
/// permission-flag pair Shardlane derives for AutoApprove. `--help` never
/// launches the TUI. Cached for the process; capability surfaces must not
/// claim Codex permission modes until this probe passes on the real CLI.
pub fn codex_permission_flags_supported() -> bool {
    static PROBE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *PROBE.get_or_init(|| {
        let args = agent_startup_args(
            AgentId::Codex,
            AgentLaunchMode::Build,
            AgentPermission::AutoApprove,
        );
        let mut command = std::process::Command::new("codex");
        for arg in args {
            command.arg(arg);
        }
        command.arg("--help");
        match command.output() {
            Ok(output) if output.status.success() => true,
            Ok(output) => {
                crate::diagnostics::lag_log(format_args!(
                    "codex permission flags rejected by the installed CLI: {}",
                    String::from_utf8_lossy(&output.stderr).trim()
                ));
                false
            }
            Err(_) => false,
        }
    })
}

/// Verified keys that enter Plan mode after readiness for providers without a
/// CLI plan flag. This is a named-key operation on an exact Agent target, not
/// raw terminal text.
pub fn agent_post_launch_plan_keys(agent: AgentId) -> &'static [&'static str] {
    match provider_plan_support(agent) {
        ProviderPlanSupport::PostLaunchKeys => match agent {
            AgentId::Codex => &["shift+tab"],
            _ => &[],
        },
        _ => &[],
    }
}

/// Build the semantic initial prompt from the original user text. Plan intent
/// for prompt-prefix providers is expressed here; branch/attachment context is
/// appended exactly as the previous GUI builder did.
pub fn build_initial_prompt(intent: &AgentLaunchIntent, cwd: &Path) -> String {
    let mut prompt = if intent.mode == AgentLaunchMode::Plan
        && matches!(
            provider_plan_support(intent.agent),
            ProviderPlanSupport::PromptPrefix
        ) {
        format!(
            "Work in Plan mode first. Analyze the request, inspect the project, and produce a concrete plan before making changes.\n\n{}",
            intent.prompt
        )
    } else {
        intent.prompt.clone()
    };
    if !intent.branch.trim().is_empty() {
        prompt.push_str(&format!("\n\nTarget branch: {}", intent.branch));
    }
    if !intent.attachments.is_empty() {
        prompt.push_str("\n\nAttached file references:");
        for path in &intent.attachments {
            let display = path
                .strip_prefix(cwd)
                .unwrap_or(path.as_path())
                .to_string_lossy();
            prompt.push_str(&format!("\n- {display}"));
        }
    }
    prompt
}

/// Resolve which label to apply once after runtime creation: a high-confidence
/// task title when available, otherwise the provider display name.
pub fn launch_display_label(intent: &AgentLaunchIntent) -> (String, Option<String>) {
    match suggest_task_title(&intent.prompt) {
        Some(title) => (title.clone(), Some(title)),
        None => (intent.agent.display_name().to_string(), None),
    }
}

/// Canonical request fingerprint for Host launch idempotency. The semantic
/// operation id is deliberately excluded: reusing an id for another target or
/// prompt must be rejected by the operation ledger, never treated as a replay.
pub fn agent_launch_fingerprint(intent: &AgentLaunchIntent) -> String {
    format!(
        "project={}|workspace={}|branch={}|mode={:?}|permission={:?}|agent={}|prompt={}|attachments={:?}|args={:?}|skip_initial_prompt={}",
        intent.project_path,
        intent.workspace_id.as_deref().unwrap_or_default(),
        intent.branch,
        intent.mode,
        intent.permission,
        intent.agent.as_str(),
        intent.prompt,
        intent.attachments,
        intent.extra_args,
        intent.skip_initial_prompt,
    )
}

/// Execute the one canonical Agent launch transaction.
pub fn run_agent_launch<R: AgentLaunchRuntime, P: ProjectPreparation>(
    runtime: &R,
    preparation: &P,
    intent: &AgentLaunchIntent,
) -> Result<AgentLaunchOutcome, AgentLaunchFailure> {
    run_agent_launch_inner(runtime, preparation, intent)
}

/// Execute a launch through the Host process' operation ledger. Product
/// surfaces use this entry point so a response-loss retry of the same logical
/// id replays the committed target/outcome instead of creating another tab or
/// Agent. The unwrapped function above remains a deterministic test seam for
/// isolated launch mechanics.
pub fn run_agent_launch_with_ledger<R: AgentLaunchRuntime, P: ProjectPreparation>(
    runtime: &R,
    preparation: &P,
    intent: &AgentLaunchIntent,
    ledger: &crate::conversation_delivery::LaunchOperationLedger,
) -> Result<AgentLaunchOutcome, AgentLaunchFailure> {
    run_agent_launch_with_ledger_fingerprint(
        runtime,
        preparation,
        intent,
        ledger,
        agent_launch_fingerprint(intent),
    )
}

/// Shared launch-intent guard (C38): one empty-operation_id check for both
/// the ledgered and plain entry points — the ledgered path must reject before
/// a ledger entry is claimed, and the plain path has no other guard.
fn ensure_operation_id(intent: &AgentLaunchIntent) -> Result<(), AgentLaunchFailure> {
    if intent.operation_id.trim().is_empty() {
        return Err(AgentLaunchFailure::ProjectUnavailable(
            "agent launch operation_id is empty".to_string(),
        ));
    }
    Ok(())
}

/// Same launch operation seam with a caller-owned stable fingerprint. Transfer
/// briefings can contain an artifact path whose capture timestamp changes on a
/// retry; their semantic request fingerprint must therefore be computed from
/// the source/instruction, not the derived briefing text.
pub(crate) fn run_agent_launch_with_ledger_fingerprint<
    R: AgentLaunchRuntime,
    P: ProjectPreparation,
>(
    runtime: &R,
    preparation: &P,
    intent: &AgentLaunchIntent,
    ledger: &crate::conversation_delivery::LaunchOperationLedger,
    fingerprint: String,
) -> Result<AgentLaunchOutcome, AgentLaunchFailure> {
    ensure_operation_id(intent)?;
    ledger.execute(intent.operation_id.trim(), fingerprint, || {
        run_agent_launch_inner(runtime, preparation, intent)
    })
}

fn run_agent_launch_inner<R: AgentLaunchRuntime, P: ProjectPreparation>(
    runtime: &R,
    preparation: &P,
    intent: &AgentLaunchIntent,
) -> Result<AgentLaunchOutcome, AgentLaunchFailure> {
    ensure_operation_id(intent)?;
    if intent.prompt.trim().is_empty() && !intent.skip_initial_prompt {
        return Err(AgentLaunchFailure::ProjectUnavailable(
            "agent task prompt is empty".to_string(),
        ));
    }
    if intent.project_path.trim().is_empty() {
        return Err(AgentLaunchFailure::ProjectUnavailable(
            "project path is empty".to_string(),
        ));
    }

    let prepared = preparation
        .prepare(&intent.project_path, &intent.branch)
        .map_err(AgentLaunchFailure::BranchPreparationFailed)?;
    let cwd_string = prepared.cwd.to_string_lossy().into_owned();

    // Integration ensure keeps its fire-and-log policy: Deferred or a failed
    // ensure must not make launch more fragile than the previous behavior.
    if let Err(error) = ensure_provider(intent.agent) {
        lag_log(format_args!(
            "agent integration ensure failed provider={} error={error}",
            intent.agent.as_str()
        ));
    }

    // Resolve the runtime structure without touching global focus. A preferred
    // workspace from the client wins; otherwise match by project path and fall
    // back to creating the workspace at the prepared cwd.
    let (created, workspace_id) = match intent.workspace_id.as_deref() {
        Some(existing) => (
            runtime
                .create_tab_without_focus(Some(existing), &cwd_string)
                .map_err(|error| AgentLaunchFailure::RuntimeCreateFailed(error.to_string()))?,
            existing.to_string(),
        ),
        None => {
            let matched = runtime
                .workspace_id_for_path(&intent.project_path)
                .map_err(|error| AgentLaunchFailure::RuntimeCreateFailed(error.to_string()))?;
            match matched {
                Some(workspace_id) => (
                    runtime
                        .create_tab_without_focus(Some(&workspace_id), &cwd_string)
                        .map_err(|error| {
                            AgentLaunchFailure::RuntimeCreateFailed(error.to_string())
                        })?,
                    workspace_id,
                ),
                None => {
                    let workspace = runtime
                        .create_workspace_without_focus(&cwd_string)
                        .map_err(|error| {
                            AgentLaunchFailure::RuntimeCreateFailed(error.to_string())
                        })?;
                    let workspace_id = workspace.workspace.workspace_id.clone();
                    (
                        TabCreatedResult {
                            tab: workspace.tab,
                            root_pane: workspace.root_pane,
                        },
                        workspace_id,
                    )
                }
            }
        }
    };
    let tab_id = created.tab.tab_id.clone();
    let pane_id = created.root_pane.pane_id.clone();

    // One deterministic rename: task title when high-confidence, provider name
    // otherwise. Failures only leave a diagnostic; they never block launch.
    let (label, task_title) = launch_display_label(intent);
    if let Err(error) = runtime.rename_tab(&tab_id, &label) {
        lag_log(format_args!(
            "agent launch rename_tab failed tab={tab_id} label={label} error={error}"
        ));
    }
    if let Err(error) = runtime.rename_pane(&pane_id, &label) {
        lag_log(format_args!(
            "agent launch rename_pane failed pane={pane_id} label={label} error={error}"
        ));
    }

    // Start the Agent through Herdr with Host-derived argv. The shell must be
    // interactive first; herdr's own "available shell" check can still race a
    // fresh pane's initialization, so the READ-ONLY readiness gate is retried
    // once after re-settling (no Agent exists yet). `agent.start` itself is a
    // mutation and executes exactly once (AC-01): an uncertain response is
    // reconciled through the typed readiness verification below, never
    // repeated.
    let mut launch_args = intent.extra_args.clone();
    launch_args.extend(agent_startup_args(
        intent.agent,
        intent.mode,
        intent.permission,
    ));
    // Herdr requires a unique lowercase identifier here; the display label is
    // applied through the rename seam below.
    // Derive the runtime name from the semantic operation id rather than a
    // fresh timestamp.  A retry of the same operation therefore addresses the
    // same launch identity and cannot silently mint a second name/Agent.
    let operation_name: String = intent
        .operation_id
        .chars()
        .filter(|character| character.is_ascii_alphanumeric() || *character == '-')
        .take(32)
        .collect();
    let operation_name = if operation_name.is_empty() {
        "operation".to_string()
    } else {
        operation_name
    };
    let agent_name = format!("{}-{operation_name}", herdr_agent_kind(intent.agent));
    let start_params = AgentStartParams {
        name: agent_name,
        kind: herdr_agent_kind(intent.agent).to_string(),
        pane_id: pane_id.clone(),
        args: launch_args,
        timeout_ms: Some(AGENT_START_TIMEOUT_MS),
    };
    let start_outcome = {
        let gate = runtime
            .wait_shell_ready(&pane_id, SHELL_READY_TIMEOUT_MS)
            .or_else(|first_gate_error| {
                std::thread::sleep(Duration::from_millis(500));
                runtime
                    .wait_shell_ready(&pane_id, SHELL_READY_TIMEOUT_MS)
                    .map_err(|_| first_gate_error)
            });
        gate.and_then(|()| runtime.start_agent(&start_params))
    };
    let start_uncertain = match &start_outcome {
        Ok(_) => false,
        Err(error) => runtime.error_is_uncertain(error),
    };
    if let Err(error) = start_outcome {
        if !start_uncertain {
            // Definitive failure: the Agent never started, so the created tab
            // is unused and can be cleaned up exactly once.
            let _ = runtime.close_tab(&tab_id);
            return Err(AgentLaunchFailure::AgentStartFailed(error.to_string()));
        }
        lag_log(format_args!(
            "agent launch start response uncertain pane={pane_id}; reconciling the typed occupant without repeating the mutation"
        ));
        // Fall through: the readiness verification below is the reconciliation.
        // If it cannot prove the intended provider owns this pane, surface an
        // uncertain failure WITHOUT closing the tab — a valid first Agent may
        // already be running in it.
    }

    // Readiness: Herdr's own wait plus typed identity verification. For an
    // uncertain start this doubles as the AC-01 reconciliation: success proves
    // the exact pane/provider/session actually started.
    // P0-04: after the start commit, every phase failure carries the created
    // structure so callers reconcile instead of re-launching.
    let agent_created =
        |phase: CreatedAgentPhase, detail: String| AgentLaunchFailure::AgentCreated {
            agent_ref: AgentRef::new(pane_id.clone()),
            tab_id: tab_id.clone(),
            pane_id: pane_id.clone(),
            phase,
            detail,
        };
    let readiness_failure = |message: String| {
        if start_uncertain {
            AgentLaunchFailure::AgentStartUncertain {
                agent_ref: AgentRef::new(pane_id.clone()),
                tab_id: tab_id.clone(),
                pane_id: pane_id.clone(),
                detail: message,
            }
        } else {
            agent_created(CreatedAgentPhase::NotReady, message)
        }
    };
    runtime
        .wait_agent_idle(&pane_id, READINESS_TIMEOUT_MS)
        .map_err(|error| readiness_failure(error.to_string()))?;
    // Typed identity verification: the intended provider must own this pane,
    // either through its agent_session or (for providers without a typed
    // session) through the Herdr display-agent field. The read retries inside
    // a bounded window because typed-session registration lags the readiness
    // signal; a single read here raced cold CLI boots into false failures.
    let verify_deadline =
        std::time::Instant::now() + Duration::from_millis(IDENTITY_VERIFY_TIMEOUT_MS);
    loop {
        let ready_agent = runtime
            .agent_by_pane(&pane_id)
            .map_err(|error| readiness_failure(error.to_string()))?;
        let Some(agent) = ready_agent else {
            if std::time::Instant::now() >= verify_deadline {
                return Err(readiness_failure(
                    "started agent is not present in the runtime projection".to_string(),
                ));
            }
            std::thread::sleep(Duration::from_millis(IDENTITY_VERIFY_POLL_MS));
            continue;
        };
        let session_matches = agent
            .agent_session
            .as_ref()
            .and_then(|session| agent_id_from_herdr_kind(&session.agent))
            .or_else(|| agent.agent.as_deref().and_then(agent_id_from_herdr_kind))
            == Some(intent.agent);
        if session_matches && agent.interactive_ready {
            break;
        }
        if std::time::Instant::now() >= verify_deadline {
            return Err(readiness_failure(format!(
                "agent identity/readiness verification failed (interactive_ready={})",
                agent.interactive_ready
            )));
        }
        std::thread::sleep(Duration::from_millis(IDENTITY_VERIFY_POLL_MS));
    }

    // Verified post-ready keys for providers that enter Plan mode that way.
    // AC-18: the user explicitly chose Plan — failing to enter it is a typed
    // launch failure surfaced before the initial prompt, never a silent
    // mode downgrade. The Agent itself keeps running in its default mode;
    // the error tells the client the requested mode was not established.
    if intent.mode == AgentLaunchMode::Plan {
        let keys: Vec<String> = agent_post_launch_plan_keys(intent.agent)
            .iter()
            .map(|key| key.to_string())
            .collect();
        if !keys.is_empty() {
            if let Err(error) = runtime.send_agent_keys(&pane_id, &keys) {
                lag_log(format_args!(
                    "agent launch plan keys failed pane={pane_id} error={error}"
                ));
                return Err(agent_created(
                    CreatedAgentPhase::PlanSetup,
                    error.to_string(),
                ));
            }
        }
    }

    // Exactly one semantic initial prompt — skipped only when the caller
    // explicitly launched without one (instruction-less History resume).
    // P0-04: a failed initial prompt NEVER describes the launch as "not
    // started" — the Agent exists; uncertainty is carried explicitly so a
    // retry reconciles instead of creating a duplicate Agent.
    if !intent.skip_initial_prompt {
        let prompt = build_initial_prompt(intent, &prepared.cwd);
        if let Err(error) = runtime.prompt_agent_once(&pane_id, &prompt) {
            let detail = error.to_string();
            // C07: uncertainty is a TYPED property of the runtime error
            // (`HerdrError::DeliveryUncertain` is produced at the source for
            // every "written but not read / timed out" prompt outcome), so
            // classification must not guess from English substrings in the
            // Display text.
            let phase = if runtime.error_is_uncertain(&error) {
                CreatedAgentPhase::InitialPromptUncertain
            } else {
                CreatedAgentPhase::InitialPrompt
            };
            return Err(agent_created(phase, detail));
        }
    }

    // Bind the exact Conversation identity from fresh runtime state. Binding
    // failure is degraded success (Terminal presentation), not launch failure.
    let bound = runtime
        .agent_by_pane(&pane_id)
        .ok()
        .flatten()
        .and_then(|agent| {
            let revision = agent.revision;
            agent
                .agent_session
                .as_ref()
                .cloned()
                .map(|session| (session, revision))
        })
        .and_then(|(session, revision)| {
            continued_identity(
                AgentRef::new(pane_id.clone()),
                herdr_agent_kind(intent.agent),
                &session,
                revision,
            )
            .ok()
        });

    let layout = runtime.pane_layout(&pane_id).map_err(|error| {
        agent_created(
            CreatedAgentPhase::Projection,
            format!("post-launch pane layout projection failed: {error}"),
        )
    })?;

    Ok(AgentLaunchOutcome {
        agent_ref: AgentRef::new(pane_id.clone()),
        pane_id,
        tab_id,
        workspace_id,
        identity: bound,
        task_title,
        created,
        layout,
    })
}

/// Production adapter over the live Herdr client.
impl AgentLaunchRuntime for HerdrClient {
    type Error = HerdrError;

    fn create_tab_without_focus(
        &self,
        workspace_id: Option<&str>,
        cwd: &str,
    ) -> Result<TabCreatedResult, Self::Error> {
        self.create_tab_at_with_focus(workspace_id, Some(cwd), false)
    }

    fn create_workspace_without_focus(
        &self,
        cwd: &str,
    ) -> Result<WorkspaceCreatedResult, Self::Error> {
        self.create_workspace_at_with_focus(Some(cwd), false)
    }

    fn workspace_id_for_path(&self, project_path: &str) -> Result<Option<String>, Self::Error> {
        // C32: this correlation only reads workspace metadata — the
        // navigation projection (workspace.list + tab.list) is enough; the
        // host_bootstrap_state fan-out (one pane.list per workspace) is not.
        let state = self.navigation_state()?;
        Ok(state
            .workspaces
            .iter()
            .find(|workspace| {
                workspace
                    .cwd
                    .as_deref()
                    .is_some_and(|cwd| crate::project_paths_match(cwd, project_path))
            })
            .map(|workspace| workspace.workspace_id.clone()))
    }

    fn start_agent(&self, params: &AgentStartParams) -> Result<AgentStartedResult, Self::Error> {
        HerdrClient::start_agent(self, params)
    }

    fn wait_agent_idle(&self, target: &str, timeout_ms: u64) -> Result<(), Self::Error> {
        // Claude Code settles a finished turn in `done` and may never report
        // `idle` again, so sendable readiness must accept both.
        self.wait_for_agent(&AgentWaitParams {
            target: target.to_string(),
            until: vec![HerdrAgentStatus::Idle, HerdrAgentStatus::Done],
            timeout_ms: Some(timeout_ms),
        })
        .map(|_| ())
    }

    fn error_is_uncertain(&self, error: &Self::Error) -> bool {
        match error {
            HerdrError::DeliveryUncertain(_) | HerdrError::ApiTimeout(_) => true,
            HerdrError::Io(io) => matches!(
                io.kind(),
                std::io::ErrorKind::WouldBlock | std::io::ErrorKind::TimedOut
            ),
            _ => false,
        }
    }

    fn wait_shell_ready(&self, pane_id: &str, timeout_ms: u64) -> Result<(), Self::Error> {
        let started = std::time::Instant::now();
        loop {
            if let Ok(info) = self.pane_process_info(pane_id) {
                if let Some(shell_pid) = info.shell_pid {
                    if info
                        .foreground_processes
                        .iter()
                        .all(|process| process.pid == shell_pid)
                    {
                        return Ok(());
                    }
                }
            }
            if started.elapsed() >= Duration::from_millis(timeout_ms) {
                return Err(HerdrError::Api(format!(
                    "pane {pane_id} shell did not become ready within {timeout_ms}ms"
                )));
            }
            std::thread::sleep(Duration::from_millis(100));
        }
    }

    fn wait_agent_settled(
        &self,
        target: &str,
        timeout_ms: u64,
    ) -> Result<SettledStatus, Self::Error> {
        let agent = self.wait_for_agent(&AgentWaitParams {
            target: target.to_string(),
            until: vec![
                HerdrAgentStatus::Idle,
                HerdrAgentStatus::Done,
                HerdrAgentStatus::Blocked,
            ],
            timeout_ms: Some(timeout_ms),
        })?;
        match crate::agent_sendability(&agent) {
            crate::AgentSendability::NeedsTerminal => Ok(SettledStatus::Blocked),
            crate::AgentSendability::Sendable => Ok(SettledStatus::Idle),
            crate::AgentSendability::MidTurn | crate::AgentSendability::Unknown => Err(
                HerdrError::Api("agent settled with an unproven status".to_string()),
            ),
        }
    }

    fn agent_by_pane(&self, pane_id: &str) -> Result<Option<crate::herdr::Agent>, Self::Error> {
        Ok(self
            .agents()?
            .into_iter()
            .find(|agent| agent.pane_id.as_deref() == Some(pane_id)))
    }

    fn prompt_agent_once(&self, target: &str, text: &str) -> Result<(), Self::Error> {
        // Herdr's prompt submits via a delayed encoded Enter; the wait keeps
        // the submission attached to the connection and turns a swallowed
        // submit into a typed `agent_prompt_stalled` failure instead of a
        // silently parked composer. The first Working/Done/Blocked transition
        // confirms delivery without waiting for the whole turn.
        self.prompt_agent_confirmed(&AgentPromptParams {
            target: target.to_string(),
            text: text.to_string(),
            wait: Some(crate::herdr::AgentPromptWaitOptions {
                until: vec![
                    HerdrAgentStatus::Working,
                    HerdrAgentStatus::Done,
                    HerdrAgentStatus::Blocked,
                ],
                timeout_ms: Some(PROMPT_SUBMIT_TIMEOUT_MS),
            }),
        })
        .map(|_| ())
    }

    fn send_agent_keys(&self, target: &str, keys: &[String]) -> Result<(), Self::Error> {
        self.send_agent_keys(&AgentSendKeysParams {
            target: target.to_string(),
            keys: keys.to_vec(),
        })
    }

    fn rename_tab(&self, tab_id: &str, label: &str) -> Result<(), Self::Error> {
        HerdrClient::rename_tab(self, tab_id, label)
    }

    fn rename_pane(&self, pane_id: &str, label: &str) -> Result<(), Self::Error> {
        HerdrClient::rename_pane(self, pane_id, label)
    }

    fn close_tab(&self, tab_id: &str) -> Result<(), Self::Error> {
        HerdrClient::close_tab(self, tab_id)
    }

    fn pane_layout(&self, pane_id: &str) -> Result<crate::herdr::PaneLayout, Self::Error> {
        HerdrClient::pane_layout(self, pane_id)
    }
}

/// Git worktree preparation under a Shardlane-owned root. Preserves the exact
/// semantics of the previous GUI seam: empty/current branch → project path,
/// existing worktree for branch → reuse, otherwise `git worktree add` into a
/// sanitized stable path. No destructive cleanup in v1.
#[derive(Clone, Debug)]
pub struct GitWorktreePreparation {
    worktree_root: PathBuf,
}

impl GitWorktreePreparation {
    pub fn new(worktree_root: impl Into<PathBuf>) -> Self {
        Self {
            worktree_root: worktree_root.into(),
        }
    }

    fn branch_worktree_path(&self, project_path: &str, branch: &str) -> PathBuf {
        use std::hash::{Hash, Hasher};
        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        project_path.hash(&mut hasher);
        let project_key = format!("{:016x}", hasher.finish());
        let branch_name = branch
            .chars()
            .map(|character| {
                if character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.') {
                    character
                } else {
                    '_'
                }
            })
            .collect::<String>();
        self.worktree_root.join(project_key).join(branch_name)
    }
}

fn git_output(project_path: &str, args: &[&str]) -> Result<String, String> {
    let output = std::process::Command::new("git")
        .arg("-C")
        .arg(project_path)
        .args(args)
        .output()
        .map_err(|error| error.to_string())?;
    if !output.status.success() {
        return Err(String::from_utf8_lossy(&output.stderr).trim().to_string());
    }
    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

fn existing_worktree_for_branch(project_path: &str, branch: &str) -> Option<PathBuf> {
    let output = git_output(project_path, &["worktree", "list", "--porcelain"]).ok()?;
    let mut worktree = None::<PathBuf>;
    for line in output.lines().chain(std::iter::once("")) {
        if let Some(path) = line.strip_prefix("worktree ") {
            worktree = Some(PathBuf::from(path));
            continue;
        }
        if let Some(name) = line.strip_prefix("branch refs/heads/") {
            if name == branch {
                return worktree.clone();
            }
        }
        if line.is_empty() {
            worktree = None;
        }
    }
    None
}

impl ProjectPreparation for GitWorktreePreparation {
    fn prepare(&self, project_path: &str, branch: &str) -> Result<PreparedProject, String> {
        if branch.trim().is_empty() {
            return Ok(PreparedProject {
                cwd: PathBuf::from(project_path),
                worktree_created: false,
            });
        }
        let current = git_output(project_path, &["branch", "--show-current"]).unwrap_or_default();
        if current.trim() == branch {
            return Ok(PreparedProject {
                cwd: PathBuf::from(project_path),
                worktree_created: false,
            });
        }
        if let Some(existing) = existing_worktree_for_branch(project_path, branch) {
            return Ok(PreparedProject {
                cwd: existing,
                worktree_created: false,
            });
        }
        let destination = self.branch_worktree_path(project_path, branch);
        if let Some(parent) = destination.parent() {
            std::fs::create_dir_all(parent).map_err(|error| error.to_string())?;
        }
        let output = std::process::Command::new("git")
            .arg("-C")
            .arg(project_path)
            .args(["worktree", "add"])
            .arg(&destination)
            .arg(branch)
            .output()
            .map_err(|error| error.to_string())?;
        if !output.status.success() {
            return Err(format!(
                "Unable to prepare branch {branch}: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            ));
        }
        Ok(PreparedProject {
            cwd: destination,
            worktree_created: true,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::RefCell;

    #[derive(Default)]
    struct MockLaunchRuntime {
        start_fail: bool,
        start_uncertain: bool,
        keys_fail: bool,
        wait_fail: bool,
        prompt_fail: bool,
        layout_fail: bool,
        ready_agent: Option<crate::herdr::Agent>,
        start_calls: RefCell<u8>,
        start_args: RefCell<Vec<Vec<String>>>,
        prompt_calls: RefCell<u8>,
        prompt_texts: RefCell<Vec<String>>,
        keys: RefCell<Vec<Vec<String>>>,
        renames: RefCell<Vec<String>>,
        close_tab_calls: RefCell<u8>,
        create_tab_calls: RefCell<u8>,
    }

    struct MockError(&'static str);
    impl fmt::Display for MockError {
        fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
            formatter.write_str(self.0)
        }
    }

    fn tab_created() -> TabCreatedResult {
        TabCreatedResult {
            tab: crate::herdr::Tab {
                tab_id: "tab-1".into(),
                workspace_id: Some("ws-1".into()),
                label: None,
                title: None,
                terminal_title: None,
                agent_status: None,
                pane_count: None,
                focused: false,
            },
            root_pane: crate::herdr::Pane {
                pane_id: "pane-1".into(),
                ..Default::default()
            },
        }
    }

    fn agent_with_session(interactive_ready: bool) -> crate::herdr::Agent {
        agent_with_kind_session("claude", interactive_ready)
    }

    fn agent_with_kind_session(herdr_kind: &str, interactive_ready: bool) -> crate::herdr::Agent {
        crate::herdr::Agent {
            pane_id: Some("pane-1".into()),
            interactive_ready,
            agent_session: Some(crate::herdr::AgentSessionInfo {
                agent: herdr_kind.into(),
                kind: "id".into(),
                source: format!("herdr:{herdr_kind}"),
                value: "native-1".into(),
            }),
            revision: 3,
            ..Default::default()
        }
    }

    impl AgentLaunchRuntime for MockLaunchRuntime {
        type Error = MockError;

        fn create_tab_without_focus(
            &self,
            _workspace_id: Option<&str>,
            _cwd: &str,
        ) -> Result<TabCreatedResult, Self::Error> {
            self.create_tab_calls.replace_with(|count| *count + 1);
            Ok(tab_created())
        }

        fn create_workspace_without_focus(
            &self,
            _cwd: &str,
        ) -> Result<WorkspaceCreatedResult, Self::Error> {
            Ok(WorkspaceCreatedResult {
                workspace: crate::herdr::Workspace {
                    workspace_id: "ws-2".into(),
                    label: None,
                    cwd: None,
                    agent_status: None,
                    active_tab_id: None,
                    focused: false,
                    tab_count: None,
                    pane_count: None,
                    number: None,
                },
                tab: tab_created().tab,
                root_pane: tab_created().root_pane,
            })
        }

        fn workspace_id_for_path(
            &self,
            _project_path: &str,
        ) -> Result<Option<String>, Self::Error> {
            Ok(Some("ws-1".into()))
        }

        fn start_agent(
            &self,
            params: &AgentStartParams,
        ) -> Result<AgentStartedResult, Self::Error> {
            self.start_calls.replace_with(|count| *count + 1);
            self.start_args.borrow_mut().push(params.args.clone());
            if self.start_uncertain {
                // Response was not read (socket timeout): the start may have
                // been accepted server-side.
                return Err(MockError("start response not read"));
            }
            if self.start_fail {
                return Err(MockError("start failed"));
            }
            Ok(AgentStartedResult {
                agent: agent_with_session(true),
                _argv: Vec::new(),
            })
        }

        fn error_is_uncertain(&self, error: &Self::Error) -> bool {
            self.start_uncertain && error.0 == "start response not read"
        }

        fn wait_agent_idle(&self, _target: &str, _timeout_ms: u64) -> Result<(), Self::Error> {
            if self.wait_fail {
                return Err(MockError("not ready"));
            }
            Ok(())
        }

        fn wait_shell_ready(&self, _pane_id: &str, _timeout_ms: u64) -> Result<(), Self::Error> {
            Ok(())
        }

        fn wait_agent_settled(
            &self,
            _target: &str,
            _timeout_ms: u64,
        ) -> Result<SettledStatus, Self::Error> {
            if self.wait_fail {
                return Err(MockError("not ready"));
            }
            Ok(SettledStatus::Idle)
        }

        fn agent_by_pane(
            &self,
            _pane_id: &str,
        ) -> Result<Option<crate::herdr::Agent>, Self::Error> {
            Ok(self.ready_agent.clone())
        }

        fn prompt_agent_once(&self, _target: &str, text: &str) -> Result<(), Self::Error> {
            self.prompt_calls.replace_with(|count| *count + 1);
            self.prompt_texts.borrow_mut().push(text.to_string());
            if self.prompt_fail {
                return Err(MockError("prompt rejected"));
            }
            Ok(())
        }

        fn send_agent_keys(&self, _target: &str, keys: &[String]) -> Result<(), Self::Error> {
            self.keys.borrow_mut().push(keys.to_vec());
            if self.keys_fail {
                return Err(MockError("plan keys rejected"));
            }
            Ok(())
        }

        fn rename_tab(&self, _tab_id: &str, label: &str) -> Result<(), Self::Error> {
            self.renames.borrow_mut().push(label.to_string());
            Ok(())
        }

        fn rename_pane(&self, _pane_id: &str, label: &str) -> Result<(), Self::Error> {
            self.renames.borrow_mut().push(label.to_string());
            Ok(())
        }

        fn close_tab(&self, _tab_id: &str) -> Result<(), Self::Error> {
            self.close_tab_calls.replace_with(|count| *count + 1);
            Ok(())
        }

        fn pane_layout(&self, _pane_id: &str) -> Result<crate::herdr::PaneLayout, Self::Error> {
            if self.layout_fail {
                return Err(MockError("layout projection unavailable"));
            }
            Ok(crate::herdr::PaneLayout::default())
        }
    }

    struct FixedPreparation(PathBuf);
    impl ProjectPreparation for FixedPreparation {
        fn prepare(&self, _project_path: &str, _branch: &str) -> Result<PreparedProject, String> {
            Ok(PreparedProject {
                cwd: self.0.clone(),
                worktree_created: false,
            })
        }
    }

    fn intent(agent: AgentId) -> AgentLaunchIntent {
        AgentLaunchIntent {
            operation_id: format!("test-launch-{}", agent.as_str()),
            workspace_id: Some("ws-1".into()),
            project_path: "/work/demo".into(),
            branch: String::new(),
            mode: AgentLaunchMode::Build,
            permission: AgentPermission::AskApproval,
            agent,
            prompt: "Fix terminal scroll regression and add coverage".into(),
            attachments: Vec::new(),
            extra_args: Vec::new(),
            skip_initial_prompt: false,
        }
    }

    fn mock() -> MockLaunchRuntime {
        MockLaunchRuntime {
            ready_agent: Some(agent_with_session(true)),
            ..Default::default()
        }
    }

    fn preparation() -> FixedPreparation {
        FixedPreparation(PathBuf::from("/work/demo"))
    }

    #[test]
    fn happy_path_starts_waits_prompts_and_binds_exactly_once() {
        let runtime = mock();
        let outcome = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode))
            .unwrap_or_else(|error| panic!("launch should succeed: {error}"));
        assert_eq!(*runtime.create_tab_calls.borrow(), 1);
        assert_eq!(*runtime.start_calls.borrow(), 1);
        assert_eq!(*runtime.prompt_calls.borrow(), 1);
        assert_eq!(*runtime.close_tab_calls.borrow(), 0);
        assert_eq!(outcome.tab_id, "tab-1");
        assert_eq!(outcome.pane_id, "pane-1");
        let identity = outcome
            .identity
            .unwrap_or_else(|| panic!("semantic identity binds"));
        assert_eq!(identity.agent_ref.as_str(), "pane-1");
        assert_eq!(identity.native_session_id.as_deref(), Some("native-1"));
        assert_eq!(
            outcome.task_title.as_deref(),
            Some("Fix Terminal Scroll Regression")
        );
        // Task title is applied once to both tab and pane.
        assert_eq!(
            runtime.renames.borrow().as_slice(),
            [
                "Fix Terminal Scroll Regression",
                "Fix Terminal Scroll Regression"
            ]
        );
    }

    #[test]
    fn claude_plan_mode_starts_with_cli_permission_args() {
        let runtime = mock();
        let mut plan = intent(AgentId::ClaudeCode);
        plan.mode = AgentLaunchMode::Plan;
        run_agent_launch(&runtime, &preparation(), &plan)
            .unwrap_or_else(|error| panic!("launch should succeed: {error}"));
        assert_eq!(
            runtime.start_args.borrow()[0],
            vec!["--permission-mode".to_string(), "plan".to_string()]
        );
        // Claude expresses plan via CLI: no post-launch keys.
        assert!(runtime.keys.borrow().is_empty());
    }

    #[test]
    fn codex_plan_mode_uses_post_launch_keys_without_plan_args() {
        let mut runtime = mock();
        runtime.ready_agent = Some(agent_with_kind_session("codex", true));
        let mut plan = intent(AgentId::Codex);
        plan.mode = AgentLaunchMode::Plan;
        plan.prompt = "Ship the release checklist".into();
        run_agent_launch(&runtime, &preparation(), &plan)
            .unwrap_or_else(|error| panic!("launch should succeed: {error}"));
        assert!(runtime.start_args.borrow()[0].is_empty());
        assert_eq!(
            runtime.keys.borrow().as_slice(),
            [vec!["shift+tab".to_string()]]
        );
    }

    #[test]
    fn prompt_prefix_providers_get_plan_prefix_in_semantic_prompt() {
        let mut runtime = mock();
        runtime.ready_agent = Some(agent_with_kind_session("pi", true));
        let mut plan = intent(AgentId::Pi);
        plan.mode = AgentLaunchMode::Plan;
        run_agent_launch(&runtime, &preparation(), &plan)
            .unwrap_or_else(|error| panic!("launch should succeed: {error}"));
        assert!(runtime.keys.borrow().is_empty());
        assert!(
            runtime.prompt_texts.borrow()[0].starts_with("Work in Plan mode first."),
            "prompt-prefix providers express plan intent through the prompt"
        );
    }

    #[test]
    fn branch_and_attachments_are_appended_to_the_prompt() {
        let runtime = mock();
        let mut with_context = intent(AgentId::ClaudeCode);
        with_context.branch = "feature/search".into();
        with_context.attachments = vec![PathBuf::from("/work/demo/src/main.rs")];
        run_agent_launch(&runtime, &preparation(), &with_context)
            .unwrap_or_else(|error| panic!("launch should succeed: {error}"));
        let prompt = runtime.prompt_texts.borrow()[0].clone();
        assert!(prompt.contains("Target branch: feature/search"));
        assert!(prompt.contains("- src/main.rs"));
    }

    #[test]
    fn start_failure_closes_the_unused_tab_exactly_once_and_never_prompts() {
        let mut runtime = mock();
        runtime.start_fail = true;
        let result = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode));
        assert!(matches!(
            result,
            Err(AgentLaunchFailure::AgentStartFailed(_))
        ));
        // AC-01: a definitive start failure executes the mutation exactly once
        // (no full retry of the start after an error).
        assert_eq!(*runtime.start_calls.borrow(), 1);
        assert_eq!(*runtime.close_tab_calls.borrow(), 1);
        assert_eq!(*runtime.prompt_calls.borrow(), 0);
    }

    #[test]
    fn uncertain_start_reconciles_a_proven_occupant_without_repeating_the_mutation() {
        let mut runtime = mock();
        runtime.start_uncertain = true;
        // The readiness projection proves the intended provider already owns
        // the pane: the launch continues exactly as a normal success.
        runtime.ready_agent = Some(agent_with_session(true));
        let outcome = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode))
            .unwrap_or_else(|error| panic!("reconciled start must succeed: {error}"));
        assert_eq!(*runtime.start_calls.borrow(), 1, "mutation never repeats");
        assert_eq!(*runtime.close_tab_calls.borrow(), 0);
        assert_eq!(*runtime.prompt_calls.borrow(), 1);
        assert!(outcome.identity.is_some());
    }

    #[test]
    fn uncertain_start_without_proof_fails_open_without_tearing_down_the_tab() {
        let mut runtime = mock();
        runtime.start_uncertain = true;
        // No agent in the pane projection: the start cannot be proven, but a
        // valid first Agent may still be starting — never close the tab and
        // never repeat the mutation.
        runtime.ready_agent = None;
        let result = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode));
        assert!(matches!(
            result,
            Err(AgentLaunchFailure::AgentStartUncertain { .. })
        ));
        assert_eq!(*runtime.start_calls.borrow(), 1);
        assert_eq!(*runtime.close_tab_calls.borrow(), 0);
        assert_eq!(*runtime.prompt_calls.borrow(), 0);
    }

    #[test]
    fn readiness_failure_keeps_the_runtime_and_never_prompts() {
        let mut runtime = mock();
        runtime.wait_fail = true;
        let result = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode));
        assert!(matches!(
            result,
            Err(AgentLaunchFailure::AgentCreated {
                phase: CreatedAgentPhase::NotReady,
                ..
            })
        ));
        assert_eq!(*runtime.close_tab_calls.borrow(), 0);
        assert_eq!(*runtime.prompt_calls.borrow(), 0);
    }

    #[test]
    fn non_interactive_ready_agent_is_not_ready() {
        let mut runtime = mock();
        runtime.ready_agent = Some(agent_with_session(false));
        let result = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode));
        assert!(matches!(
            result,
            Err(AgentLaunchFailure::AgentCreated {
                phase: CreatedAgentPhase::NotReady,
                ..
            })
        ));
        assert_eq!(*runtime.prompt_calls.borrow(), 0);
    }

    #[test]
    fn codex_autoapprove_flags_pass_the_installed_cli_when_present() {
        // R2-13: the unit-locked argv must also be accepted by the real
        // installed Codex CLI (skipped when Codex is not installed).
        if std::process::Command::new("codex")
            .arg("--version")
            .output()
            .map(|output| output.status.success())
            .unwrap_or(false)
        {
            assert!(
                codex_permission_flags_supported(),
                "the derived Codex AutoApprove flags must be valid for the installed CLI"
            );
        } else {
            eprintln!("skipping: codex CLI not installed");
        }
    }

    #[test]
    fn plan_mode_setup_failure_is_typed_and_never_prompts() {
        // AC-18: a rejected Plan-mode setup must surface truthfully before the
        // initial prompt instead of silently continuing in the default mode.
        let mut runtime = mock();
        runtime.ready_agent = Some(agent_with_kind_session("codex", true));
        runtime.keys_fail = true;
        let mut plan = intent(AgentId::Codex);
        plan.mode = AgentLaunchMode::Plan;
        let result = run_agent_launch(&runtime, &preparation(), &plan);
        // P0-04: the start committed, so the failure carries the created
        // structure and the exact phase.
        assert!(matches!(
            result,
            Err(AgentLaunchFailure::AgentCreated {
                phase: CreatedAgentPhase::PlanSetup,
                ..
            })
        ));
        assert_eq!(
            *runtime.prompt_calls.borrow(),
            0,
            "no prompt after mode failure"
        );
    }

    #[test]
    fn prompt_failure_keeps_the_agent_and_reports_the_phase() {
        let mut runtime = mock();
        runtime.prompt_fail = true;
        let result = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode));
        assert!(matches!(
            result,
            Err(AgentLaunchFailure::AgentCreated {
                phase: CreatedAgentPhase::InitialPrompt,
                ..
            })
        ));
        assert_eq!(*runtime.close_tab_calls.borrow(), 0);
        assert_eq!(*runtime.prompt_calls.borrow(), 1);
    }

    #[test]
    fn post_commit_layout_failure_is_reconcileable_and_not_retryable() {
        let mut runtime = mock();
        runtime.layout_fail = true;
        let result = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode));
        assert!(matches!(
            result,
            Err(AgentLaunchFailure::AgentCreated {
                phase: CreatedAgentPhase::Projection,
                ..
            })
        ));
        assert_eq!(*runtime.start_calls.borrow(), 1);
        assert_eq!(*runtime.prompt_calls.borrow(), 1);
        assert_eq!(*runtime.close_tab_calls.borrow(), 0);
    }

    #[test]
    fn missing_semantic_session_is_degraded_success_not_failure() {
        let mut runtime = mock();
        let mut agent = agent_with_session(true);
        // Session-less provider: Herdr still identifies the kind through the
        // display-agent field, so the Agent is ready — only Chat binding degrades.
        agent.agent_session = None;
        agent.agent = Some("claude".into());
        runtime.ready_agent = Some(agent);
        let outcome = run_agent_launch(&runtime, &preparation(), &intent(AgentId::ClaudeCode))
            .unwrap_or_else(|error| panic!("launch itself succeeds: {error}"));
        assert!(outcome.identity.is_none());
        assert_eq!(*runtime.prompt_calls.borrow(), 1);
    }

    #[test]
    fn empty_prompt_fails_validation_before_any_runtime_call() {
        let runtime = mock();
        let mut empty = intent(AgentId::ClaudeCode);
        empty.prompt = "   ".into();
        let result = run_agent_launch(&runtime, &preparation(), &empty);
        assert!(matches!(
            result,
            Err(AgentLaunchFailure::ProjectUnavailable(_))
        ));
        assert_eq!(*runtime.create_tab_calls.borrow(), 0);
    }

    #[test]
    fn missing_workspace_preference_reuses_matched_workspace() {
        let runtime = mock();
        let mut no_preference = intent(AgentId::ClaudeCode);
        no_preference.workspace_id = None;
        let outcome = run_agent_launch(&runtime, &preparation(), &no_preference)
            .unwrap_or_else(|error| panic!("launch should succeed: {error}"));
        assert_eq!(outcome.workspace_id, "ws-1");
        assert_eq!(*runtime.create_tab_calls.borrow(), 1);
    }

    #[test]
    fn weak_prompts_keep_the_provider_display_label() {
        let mut runtime = mock();
        runtime.ready_agent = Some(agent_with_kind_session("pi", true));
        let mut weak = intent(AgentId::Pi);
        weak.prompt = "Continue".into();
        let outcome = run_agent_launch(&runtime, &preparation(), &weak)
            .unwrap_or_else(|error| panic!("launch should succeed: {error}"));
        assert_eq!(outcome.task_title, None);
        assert_eq!(runtime.renames.borrow().as_slice(), ["Pi", "Pi"]);
    }

    #[test]
    fn startup_args_match_provider_contracts() {
        assert_eq!(
            agent_startup_args(
                AgentId::ClaudeCode,
                AgentLaunchMode::Build,
                AgentPermission::FullAccess
            ),
            vec![
                "--permission-mode".to_string(),
                "bypassPermissions".to_string()
            ]
        );
        assert_eq!(
            agent_startup_args(
                AgentId::Codex,
                AgentLaunchMode::Build,
                AgentPermission::AutoApprove
            ),
            // R2-13: version-stable approval+sandbox pair (both `--full-auto`
            // and `--approve-for-me` are rejected by some installed versions).
            vec![
                "--sandbox".to_string(),
                "workspace-write".to_string(),
                "--ask-for-approval".to_string(),
                "never".to_string(),
            ]
        );
        assert_eq!(
            agent_startup_args(
                AgentId::Gemini,
                AgentLaunchMode::Plan,
                AgentPermission::AskApproval
            ),
            vec!["--approval-mode=plan".to_string()]
        );
        assert!(agent_startup_args(
            AgentId::Pi,
            AgentLaunchMode::Plan,
            AgentPermission::FullAccess
        )
        .is_empty());
    }

    #[test]
    fn worktree_paths_are_stable_and_sanitized() {
        let preparation = GitWorktreePreparation::new(PathBuf::from("/data/worktrees"));
        let first = preparation.branch_worktree_path("/work/demo", "feature/a");
        let second = preparation.branch_worktree_path("/work/demo", "feature/a");
        assert_eq!(first, second);
        assert!(first.starts_with("/data/worktrees"));
        assert!(first.ends_with("feature_a"));
    }
}
