//! Host-owned History continuation planner and transaction.
//!
//! [INPUT]: a canonical History `ConversationId`, a required stable
//! operation id, an optional target Provider, an optional continuation
//! instruction, an optional Project override; runtime facts come from the
//! Herdr client and the History catalog.
//! [OUTPUT]: `plan_history_continuation` — a read-only plan in the strict
//! order AlreadyLive → NativeResume → ContextTransfer →
//! NeedsProjectSelection → Unsupported; plus `continue_history_conversation`
//! — the plan-driven execution transaction (reusing the M2 launch and M5
//! transfer engines and their operation ledger; AlreadyLive never creates a
//! duplicate Agent).
//! [POS]: plan M6 / audit AF-01/AF-02/AF-09/AF-10. Planning precedes any
//! runtime mutation; NeedsProjectSelection is returned when the Project
//! cannot be resolved safely. Remote and the native GUI only consume this
//! service and own no Continue policy.

use crate::agent_launch::{
    AgentLaunchIntent, AgentLaunchMode, AgentLaunchOutcome, AgentLaunchRuntime, AgentPermission,
    ProjectPreparation,
};
use crate::context_transfer::{
    run_context_transfer_with_ledger, ContextTransferFailure, ContextTransferOutcome,
    ContextTransferRequest, ContextTransferSource,
};
use crate::conversation_delivery::ConversationDeliveryCoordinator;
use crate::conversation_service::ConversationServiceError;
use crate::conversations::{agent_id_from_herdr_kind, continued_identity, herdr_agent_kind};
use crate::dto::ConversationIdentity;
use crate::ids::{AgentRef, ConversationId};
use crate::services::{ContinuationStrategy, PromptDisposition};
use shardlane_history::models::{SessionFileRef, SessionMeta};
use shardlane_history::{
    prepare_resume, resume_supported, AgentId, HistoryCatalog, ResumeIntent, TransferArtifactStore,
    TransferLimits,
};

/// Exact typed correlation between an indexed History session and a Herdr
/// `AgentSessionInfo`: declared locator kind decides whether the native id or
/// the exact source path must match. Neither branch infers from cwd/mtime.
pub(crate) fn history_session_matches_herdr_identity(
    history_agent: AgentId,
    history_id: &str,
    history_path: &str,
    identity: &crate::herdr::AgentSessionInfo,
) -> bool {
    if agent_id_from_herdr_kind(&identity.agent) != Some(history_agent) {
        return false;
    }
    match identity.kind.as_str() {
        "id" => identity.value == history_id,
        "path" => identity.value == history_path,
        _ => false,
    }
}

/// One planned continuation. Produced by a read-only pass; no runtime mutation
/// has happened when it is returned.
#[derive(Clone, Debug)]
pub enum ContinuationPlan {
    /// The exact source session is already represented by a live Herdr Agent.
    AlreadyLive {
        agent_ref: AgentRef,
        identity: ConversationIdentity,
    },
    /// Same provider with an exact resumable native session; executed through
    /// the canonical launch transaction with resume args. Native resume is
    /// based on exact provider/native semantics and does NOT require a
    /// readable transfer source (AC-09).
    NativeResume {
        session: SessionMeta,
        resume_args: Vec<String>,
    },
    /// Different provider (or same provider without exact native resume); the
    /// M5 lossless engine transfers the complete context.
    ContextTransfer {
        session: SessionMeta,
        source: SessionFileRef,
        target: AgentId,
    },
    /// No safe Project is known; the client must resolve one before any
    /// runtime mutation.
    NeedsProjectSelection,
    /// No exact source/target strategy exists; fails closed with a reason.
    Unsupported { reason: String },
}

/// Read-only planning request.
#[derive(Clone, Debug)]
pub struct ContinuationRequest {
    /// Stable identity of this semantic Continue operation.  It is supplied
    /// by the caller (or generated by a transport adapter for legacy clients)
    /// and must never be derived from the Conversation id.
    pub operation_id: String,
    pub conversation_id: ConversationId,
    /// `None` = the source provider.
    pub target_provider: Option<AgentId>,
    /// Optional user continuation instruction. Empty is valid.
    pub instruction: Option<String>,
    /// Project path override once a client resolved the picker choice.
    pub project_override: Option<String>,
}

/// Executor dependencies shared with the service layer.
pub struct ContinuationDeps<'a, R: AgentLaunchRuntime, P: ProjectPreparation> {
    pub runtime: &'a R,
    pub preparation: &'a P,
    pub artifact_store: &'a TransferArtifactStore,
    pub transfer_limits: &'a TransferLimits,
    /// R2-02/CR-05: continuation instructions submit through the same
    /// authoritative Host prompt transaction (and its delivery coordinator)
    /// as Desktop Chat and Remote/Mobile.
    pub delivery: &'a std::sync::Arc<ConversationDeliveryCoordinator>,
}

/// Result of one executed continuation.
#[derive(Clone, Debug)]
pub enum ContinuationResult {
    /// The exact live Agent was reused; no new Agent exists. When an
    /// instruction was supplied, its disposition is reported.
    ReusedLive {
        identity: ConversationIdentity,
        instruction_disposition: Option<PromptDisposition>,
    },
    /// A new Agent was created (native resume or context transfer) through the
    /// canonical launch transaction; the briefing (if any) was the single
    /// initial prompt.
    Launched {
        strategy: ContinuationStrategy,
        outcome: Box<AgentLaunchOutcome>,
        briefing_sha256: Option<String>,
    },
    /// Planning requires a Project before any mutation.
    NeedsProjectSelection,
}

/// Plan one History continuation. Read-only: safe to call for pickers, gating,
/// and pre-flight explanation.
pub fn plan_history_continuation(
    client: &crate::herdr::HerdrClient,
    catalog: &HistoryCatalog,
    request: &ContinuationRequest,
) -> Result<ContinuationPlan, ConversationServiceError> {
    let key = match crate::resolve_conversation_id(&request.conversation_id) {
        Ok(crate::ConversationLocator::History(key)) => key,
        Ok(crate::ConversationLocator::Live(_))
        | Ok(crate::ConversationLocator::LiveSession { .. }) => {
            return Ok(ContinuationPlan::Unsupported {
                reason: "continue requires a history conversation".to_string(),
            })
        }
        Err(error) => {
            return Err(ConversationServiceError::Invalid(error.to_string()));
        }
    };
    let session = crate::conversations::HistoryConversationService::new(catalog)
        .session(&key)
        .map_err(ConversationServiceError::Runtime)?
        .ok_or_else(|| ConversationServiceError::NotFound("conversation not found".to_string()))?;

    // The requested target (default: the source provider) gates the
    // AlreadyLive strategy — continuing a live session with a DIFFERENT
    // provider is a ContextTransfer, never a prompt to the live Agent.
    let target = request.target_provider.unwrap_or(session.agent);

    // 1. AlreadyLive: exact same session already has a live Herdr Agent and
    // the continuation targets the same provider.
    if target == session.agent {
        if let Some(agent) = client
            .agents()
            .map_err(ConversationServiceError::Herdr)?
            .into_iter()
            .find(|agent| {
                agent.agent_session.as_ref().is_some_and(|identity| {
                    history_session_matches_herdr_identity(
                        session.agent,
                        &session.id,
                        &session.file_path,
                        identity,
                    )
                })
            })
        {
            let pane_id = agent.pane_id.clone().ok_or_else(|| {
                ConversationServiceError::Runtime("active session has no pane target".to_string())
            })?;
            let typed = agent.agent_session.clone().ok_or_else(|| {
                ConversationServiceError::Runtime(
                    "active session has no typed provider session identity".to_string(),
                )
            })?;
            let identity = continued_identity(
                AgentRef::new(pane_id),
                herdr_agent_kind(session.agent),
                &typed,
                agent.revision,
            )
            .map_err(|error| ConversationServiceError::Runtime(error.to_string()))?;
            return Ok(ContinuationPlan::AlreadyLive {
                agent_ref: identity.agent_ref.clone(),
                identity,
            });
        }
    }

    // Project resolution precedes any runtime mutation (AC-10): an explicit
    // user-selected override wins even over a non-empty stored path, and a
    // stale stored path can be repaired by the override on retry.
    let project_path = resolve_continuation_project(
        (!session.project_path.trim().is_empty()).then(|| session.project_path.clone()),
        request
            .project_override
            .as_deref()
            .map(str::trim)
            .filter(|path| !path.is_empty())
            .map(str::to_string),
    );
    let Some(project_path) = project_path else {
        return Ok(ContinuationPlan::NeedsProjectSelection);
    };
    let session_with_project = SessionMeta {
        project_path,
        ..session.clone()
    };

    // 2. NativeResume: same provider with exact resumable native session.
    // Exact resume is provider/native-session semantics only — a missing or
    // stale transfer source must not block it (AC-09).
    if target == session.agent && resume_supported(session.agent) {
        let resume_args = prepare_resume(ResumeIntent::from_session(&session_with_project))
            .map_err(ConversationServiceError::Runtime)?
            .args;
        return Ok(ContinuationPlan::NativeResume {
            session: session_with_project,
            resume_args,
        });
    }

    // 3. ContextTransfer: different provider, or same provider without exact
    // native resume. Only this strategy requires the lossless source.
    let Some(source) = catalog
        .transcript_source(&key)
        .map_err(|error| ConversationServiceError::Runtime(error.to_string()))?
    else {
        return Ok(ContinuationPlan::Unsupported {
            reason: "the conversation's provider-native source is unavailable".to_string(),
        });
    };
    Ok(ContinuationPlan::ContextTransfer {
        session: session_with_project,
        source,
        target,
    })
}

/// Execute one planned continuation.
pub fn continue_history_conversation<R: AgentLaunchRuntime, P: ProjectPreparation>(
    client: &crate::herdr::HerdrClient,
    catalog: &HistoryCatalog,
    deps: &ContinuationDeps<'_, R, P>,
    request: &ContinuationRequest,
) -> Result<ContinuationResult, ConversationServiceError> {
    if request.operation_id.trim().is_empty() {
        return Err(ConversationServiceError::Invalid(
            "continuation operation_id must not be empty".to_string(),
        ));
    }
    let plan = plan_history_continuation(client, catalog, request)?;
    let instruction = request
        .instruction
        .as_deref()
        .map(str::trim)
        .filter(|text| !text.is_empty())
        .map(str::to_string);
    match plan {
        ContinuationPlan::AlreadyLive {
            agent_ref: _,
            identity,
        } => {
            // CR-03/R2-02: History AlreadyLive no longer owns a prompt state
            // machine — the instruction goes through the same authoritative
            // Host transaction (fresh occupant proof + disposition + Host
            // delivery worker) as every other client. The wire `accepted`
            // flag is derived from the disposition so NeedsTerminal never
            // looks like an accepted instruction.
            let instruction_disposition = match instruction {
                None => None,
                Some(text) => {
                    let service = crate::conversation_service::HostConversationService::new(
                        client,
                        std::path::PathBuf::new(),
                    );
                    let submission = service.submit_conversation_prompt(
                        &identity.conversation_id,
                        deps.delivery,
                        &request.operation_id,
                        &text,
                    );
                    match submission {
                        Ok(submission) => Some(submission.disposition),
                        // C07: `submit_conversation_prompt` returns a Blocked
                        // agent as `Ok(disposition: NeedsTerminal)` — the
                        // old substring arm (`Invalid(msg) if
                        // msg.contains("blocked")`) was dead, since
                        // `prompt_disposition_for_agent` settles NeedsTerminal
                        // before any error path and every typed rejection
                        // carries its own variant. Unknown states surface as
                        // `Invalid` and propagate unchanged.
                        Err(error) => return Err(error),
                    }
                }
            };
            Ok(ContinuationResult::ReusedLive {
                identity,
                instruction_disposition,
            })
        }
        ContinuationPlan::NeedsProjectSelection => Ok(ContinuationResult::NeedsProjectSelection),
        ContinuationPlan::Unsupported { reason } => Err(ConversationServiceError::Runtime(reason)),
        ContinuationPlan::NativeResume {
            session,
            resume_args,
        } => {
            let mut launch_intent = continuation_launch_intent(&session, &request.operation_id);
            launch_intent.extra_args = resume_args;
            // M6: an empty instruction is a valid Continue — resume and bind
            // the Conversation without sending any prompt.
            match instruction {
                Some(text) => launch_intent.prompt = text,
                None => launch_intent.skip_initial_prompt = true,
            }
            let outcome = crate::agent_launch::run_agent_launch_with_ledger(
                deps.runtime,
                deps.preparation,
                &launch_intent,
                deps.delivery.launch_ledger(),
            )
            .map_err(launch_failure_to_service_error)?;
            Ok(ContinuationResult::Launched {
                strategy: ContinuationStrategy::NativeResume,
                outcome: Box::new(outcome),
                briefing_sha256: None,
            })
        }
        ContinuationPlan::ContextTransfer {
            session,
            source,
            target,
        } => {
            let launch_intent = continuation_launch_intent(&session, &request.operation_id);
            let transfer_request = ContextTransferRequest {
                source: ContextTransferSource::History(source),
                target_provider: target,
                launch: launch_intent,
                instruction,
            };
            let outcome: ContextTransferOutcome = run_context_transfer_with_ledger(
                deps.runtime,
                deps.preparation,
                deps.artifact_store,
                deps.transfer_limits,
                &transfer_request,
                deps.delivery.launch_ledger(),
            )
            .map_err(|failure: ContextTransferFailure| match failure {
                ContextTransferFailure::Launch(launch) => launch_failure_to_service_error(launch),
                other => ConversationServiceError::Runtime(other.to_string()),
            })?;
            Ok(ContinuationResult::Launched {
                strategy: ContinuationStrategy::ContextTransfer,
                outcome: Box::new(outcome.launch),
                briefing_sha256: Some(outcome.briefing_sha256),
            })
        }
    }
}

/// P0-05: launch failures cross the service boundary WITHOUT erasing their
/// transaction class. Uncertainty stays `DeliveryUncertain` so Remote
/// tombstones the request id and Mobile keeps its logical id; post-commit
/// AgentCreated failures surface their reconcile semantics verbatim.
fn launch_failure_to_service_error(
    failure: crate::agent_launch::AgentLaunchFailure,
) -> ConversationServiceError {
    use crate::agent_launch::AgentLaunchFailure;
    match failure {
        AgentLaunchFailure::AgentStartUncertain {
            agent_ref,
            tab_id,
            pane_id,
            detail,
        } => ConversationServiceError::AgentCreated {
            agent_ref,
            tab_id,
            pane_id,
            phase: crate::agent_launch::CreatedAgentPhase::StartUncertain,
            detail,
        },
        AgentLaunchFailure::OperationConflict(message) => {
            ConversationServiceError::Invalid(message)
        }
        AgentLaunchFailure::AgentCreated {
            agent_ref,
            tab_id,
            pane_id,
            phase,
            detail,
        } => ConversationServiceError::AgentCreated {
            agent_ref,
            tab_id,
            pane_id,
            phase,
            detail,
        },
        other => ConversationServiceError::Runtime(other.to_string()),
    }
}

fn continuation_launch_intent(session: &SessionMeta, operation_id: &str) -> AgentLaunchIntent {
    AgentLaunchIntent {
        operation_id: operation_id.to_string(),
        workspace_id: None,
        project_path: session.project_path.clone(),
        branch: String::new(),
        mode: AgentLaunchMode::Build,
        permission: AgentPermission::AskApproval,
        agent: session.agent,
        prompt: String::new(),
        attachments: Vec::new(),
        extra_args: Vec::new(),
        skip_initial_prompt: false,
    }
}

/// AC-10 project resolution: an explicit user-selected override wins first;
/// otherwise the stored path; a candidate is used only when it exists on disk,
/// and a stale stored path can be repaired by the override (and vice versa).
/// `None` → NeedsProjectSelection.
pub(crate) fn resolve_continuation_project(
    stored: Option<String>,
    project_override: Option<String>,
) -> Option<String> {
    let mut candidates: Vec<String> = Vec::new();
    if let Some(project_override) = project_override {
        candidates.push(project_override);
    }
    if let Some(stored) = stored {
        if !candidates.contains(&stored) {
            candidates.push(stored);
        }
    }
    candidates
        .into_iter()
        .find(|candidate| std::path::Path::new(candidate).read_dir().is_ok())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn correlation_uses_declared_locator_kind() {
        let id_locator = crate::herdr::AgentSessionInfo {
            agent: "claude".into(),
            kind: "id".into(),
            source: "herdr:claude".into(),
            value: "native-1".into(),
        };
        let path_locator = crate::herdr::AgentSessionInfo {
            agent: "claude".into(),
            kind: "path".into(),
            source: "herdr:claude".into(),
            value: "/home/.claude/s1.jsonl".into(),
        };
        assert!(history_session_matches_herdr_identity(
            AgentId::ClaudeCode,
            "native-1",
            "/home/.claude/s1.jsonl",
            &id_locator
        ));
        assert!(history_session_matches_herdr_identity(
            AgentId::ClaudeCode,
            "native-1",
            "/home/.claude/s1.jsonl",
            &path_locator
        ));
        assert!(!history_session_matches_herdr_identity(
            AgentId::Codex,
            "native-1",
            "/home/.claude/s1.jsonl",
            &id_locator
        ));
    }

    #[test]
    fn stale_stored_project_path_is_repaired_by_the_override() {
        // AC-10: a stale NON-EMPTY stored path used to win unconditionally and
        // block the picker; the override must repair it.
        let temp = tempfile::tempdir().unwrap_or_else(|error| panic!("{error}"));
        let valid_override = temp.path().join("valid");
        std::fs::create_dir_all(&valid_override).ok();
        let stale_stored = temp.path().join("gone");

        let resolved = resolve_continuation_project(
            Some(stale_stored.to_string_lossy().to_string()),
            Some(valid_override.to_string_lossy().to_string()),
        );
        assert_eq!(
            resolved.as_deref(),
            Some(valid_override.to_string_lossy().to_string().as_str())
        );

        // Empty path → only the override counts.
        let resolved = resolve_continuation_project(
            Some("   ".into()),
            Some(valid_override.to_string_lossy().to_string()),
        );
        assert!(resolved.is_some());

        // Both invalid/missing → NeedsProjectSelection.
        let resolved = resolve_continuation_project(
            Some(stale_stored.to_string_lossy().to_string()),
            Some(temp.path().join("also-gone").to_string_lossy().to_string()),
        );
        assert_eq!(resolved, None);

        // Valid stored path without an override still wins.
        let resolved =
            resolve_continuation_project(Some(valid_override.to_string_lossy().to_string()), None);
        assert!(resolved.is_some());
    }

    #[test]
    fn native_resume_plan_no_longer_carries_a_transfer_source() {
        // AC-09 contract marker: exact native resume must not depend on a
        // readable transfer artifact source (the field is gone from the plan).
        let plan = ContinuationPlan::NativeResume {
            session: SessionMeta {
                key: "claude-code:s1".into(),
                id: "s1".into(),
                agent: AgentId::ClaudeCode,
                title: "Demo".into(),
                project_path: "/work/demo".into(),
                project_name: "demo".into(),
                file_path: "/home/.claude/s1.jsonl".into(),
                created_at: 0,
                updated_at: 0,
                message_count: 0,
                size_bytes: 0,
                git_branch: None,
                model: None,
                tokens_used: None,
                archived: false,
                source: None,
            },
            resume_args: vec!["--resume".into()],
        };
        assert!(matches!(plan, ContinuationPlan::NativeResume { .. }));
    }
}
