//! Remote Access configuration model: the `remote` section of
//! `~/.shardlane/config.json`.
//!
//! [INPUT]: Depends on serde/serde_json (config parsing) and uuid (identity
//! generation); no GUI dependency — GUI Settings is the only writer, this
//! module only reads + generates missing identities
//! [OUTPUT]: Exposes RemoteConfig/ListenerMode/DEFAULT_REMOTE_PORT (config
//! loading layer port normalization: missing field 0 → 8757; the server
//! binding layer preserves 0=ephemeral test semantics), from_settings_value
//! (reads from ApplicationConfig JSON), overlay_env (dev/test environment
//! variable overrides), and ensure_identity (fills host_id/access_token;
//! the caller persists them)
//! [POS]: The configuration entry of shardlane-remote; B6's settings.rs
//! embeds RemoteConfig as an ApplicationConfig field whose wire format
//! matches this module's serde definitions

use serde::{Deserialize, Serialize};
use std::path::Path;

/// Remote API wire-format version. The mobile side discriminates
/// compatibility by `remote_api_version`.
pub const REMOTE_API_VERSION: u32 = 3;
/// The minimum Remote API version the mobile side accepts; hello rejects
/// downgrades below it.
pub const MIN_MOBILE_API_VERSION: u32 = 2;
/// Default listening port.
pub const DEFAULT_REMOTE_PORT: u16 = 8757;

/// Listener mode.
/// - `off`: no listener is started.
/// - `loopback`: binds 127.0.0.1 only — honored as configured (never widened
///   to 0.0.0.0), for local development.
/// - `local_network`: binds 0.0.0.0 (reachable on LAN/Tailscale — required
///   for phone access).
#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ListenerMode {
    #[default]
    Off,
    Loopback,
    LocalNetwork,
}

/// The `remote` section of `config.json`. Default is everything off (the
/// zero idle-cost invariant); port defaults to [`DEFAULT_REMOTE_PORT`]
/// (0=ephemeral only via explicit test construction).
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(default, rename_all = "snake_case")]
pub struct RemoteConfig {
    pub enabled: bool,
    pub listener_mode: ListenerMode,
    pub port: u16,
    /// Host identity stable across restarts; generated by ensure_identity
    /// the first time and persisted by the GUI.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub host_id: Option<String>,
    /// Static Bearer token (v1 loopback auth); never appears in logs.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// The externally reachable URL of the mobile web app (e.g.
    /// https://shardlane.dev.local); only used for pairing onboarding
    /// (QR/copy), never for serving. None = unconfigured; the pairing side
    /// shows onboarding instructions instead of generating a QR code.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub web_url: Option<String>,
}

impl Default for RemoteConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            listener_mode: ListenerMode::Off,
            port: DEFAULT_REMOTE_PORT,
            host_id: None,
            access_token: None,
            web_url: None,
        }
    }
}

impl RemoteConfig {
    /// Read the `remote` section from settings JSON (the content of
    /// `~/.shardlane/config.json`). Missing files, missing fields, or an
    /// unknown listener mode fall back to the default (off). An explicitly
    /// configured `loopback` is honored as-is and binds 127.0.0.1 only
    /// (see [`ListenerMode`] and [`RemoteConfig::bind_address`]).
    pub fn from_settings_value(value: &serde_json::Value) -> Self {
        match value.get("remote") {
            Some(section) => {
                let mut config =
                    serde_json::from_value::<RemoteConfig>(section.clone()).unwrap_or_default();
                if !matches!(
                    config.listener_mode,
                    ListenerMode::Off | ListenerMode::Loopback | ListenerMode::LocalNetwork
                ) {
                    config.listener_mode = ListenerMode::Off;
                    config.enabled = false;
                }
                // u16::default()=0 means an ephemeral random port at the
                // server binding layer (loopback tests rely on it), but a
                // product config missing the port field should fall back to
                // the default 8757 so the QR/pairing address matches the
                // actual listener. Explicitly writing 0 remains reserved for
                // test/integration callers.
                if config.port == 0 {
                    config.port = DEFAULT_REMOTE_PORT;
                }
                config
            }
            None => Self::default(),
        }
    }

    /// Read from a settings file path. IO/parse errors fall back to the
    /// default (off) — a broken remote config must not block desktop startup
    /// nor start a listener with unknown configuration.
    pub fn from_settings_file(path: &Path) -> Self {
        let Ok(raw) = std::fs::read_to_string(path) else {
            return Self::default();
        };
        let Ok(value) = serde_json::from_str::<serde_json::Value>(&raw) else {
            return Self::default();
        };
        Self::from_settings_value(&value)
    }

    /// Dev/test overrides: `SHARDLANE_REMOTE_TOKEN` and
    /// `SHARDLANE_REMOTE_PORT` provide values directly without config.json
    /// (used to isolate integration tests).
    pub fn overlay_env(&mut self) {
        if let Some(token) = std::env::var_os("SHARDLANE_REMOTE_TOKEN") {
            if let Some(token) = token.to_str() {
                if !token.is_empty() {
                    self.access_token = Some(token.to_string());
                }
            }
        }
        if let Ok(port) = std::env::var("SHARDLANE_REMOTE_PORT") {
            if let Ok(port) = port.parse::<u16>() {
                self.port = port;
            }
        }
    }

    /// Fill missing identities: host_id (`shardlane-host-<uuid>`) and
    /// access_token (two concatenated uuids, 256-bit entropy). Returns true
    /// when something changed and the caller must persist it.
    pub fn ensure_identity(&mut self) -> bool {
        let mut changed = false;
        if self.host_id.as_deref().is_none_or(str::is_empty) {
            self.host_id = Some(format!("shardlane-host-{}", uuid::Uuid::new_v4()));
            changed = true;
        }
        if self.access_token.as_deref().is_none_or(str::is_empty) {
            self.access_token = Some(fresh_access_token());
            changed = true;
        }
        changed
    }

    /// Rotate the access token (revokes all old clients; host_id stays
    /// stable). The caller is responsible for saving + restarting the
    /// server. Returns the new token.
    pub fn rotate_access_token(&mut self) -> String {
        let token = fresh_access_token();
        self.access_token = Some(token.clone());
        token
    }

    /// Server start eligibility: enabled + (loopback | local_network) + has
    /// a token.
    pub fn is_loopback_ready(&self) -> bool {
        self.enabled
            && matches!(
                self.listener_mode,
                ListenerMode::Loopback | ListenerMode::LocalNetwork
            )
            && self.access_token.as_deref().is_some_and(|t| !t.is_empty())
    }

    /// Bind address: loopback → 127.0.0.1, local_network → 0.0.0.0.
    pub fn bind_address(&self) -> std::net::IpAddr {
        match self.listener_mode {
            ListenerMode::LocalNetwork => std::net::IpAddr::V4(std::net::Ipv4Addr::UNSPECIFIED),
            _ => std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_remote_section_defaults_to_disabled() {
        let config = RemoteConfig::from_settings_value(&serde_json::json!({
            "version": 3,
            "workspaces": {}
        }));
        assert_eq!(config, RemoteConfig::default());
        assert!(!config.is_loopback_ready());
    }

    #[test]
    fn remote_section_round_trips() {
        let raw = serde_json::json!({
            "remote": {
                "enabled": true,
                "listener_mode": "local_network",
                "port": 9001,
                "host_id": "shardlane-host-x",
                "access_token": "secret"
            }
        });
        let config = RemoteConfig::from_settings_value(&raw);
        assert!(config.is_loopback_ready());
        assert_eq!(config.port, 9001);
        let back =
            serde_json::to_value(&config).unwrap_or_else(|error| panic!("serialize: {error}"));
        assert_eq!(back["listener_mode"], "local_network");
        assert_eq!(back["host_id"], "shardlane-host-x");
    }

    #[test]
    fn explicit_loopback_survives_load_and_binds_loopback_only() {
        let raw = serde_json::json!({
            "remote": {
                "enabled": true,
                "listener_mode": "loopback",
                "access_token": "secret"
            }
        });
        let config = RemoteConfig::from_settings_value(&raw);
        // D02: an explicitly configured Loopback must not be silently widened
        // to LocalNetwork (0.0.0.0) — it survives the load and binds
        // 127.0.0.1 only.
        assert_eq!(config.listener_mode, ListenerMode::Loopback);
        assert!(config.is_loopback_ready());
        assert_eq!(
            config.bind_address(),
            std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST)
        );
        // The round trip keeps the configured mode instead of rewriting it.
        let back =
            serde_json::to_value(&config).unwrap_or_else(|error| panic!("serialize: {error}"));
        assert_eq!(back["listener_mode"], "loopback");
    }

    #[test]
    fn default_stays_disabled_with_no_listener() {
        // Fresh installs (missing remote section or RemoteConfig::default())
        // keep today's effective behavior: disabled, no listener at all.
        // The default is deliberately NOT LocalNetwork: the `enabled: false`
        // gate is what keeps a fresh install idle, and a listener-mode
        // default of LocalNetwork would flip the serde container-default for
        // a hand-written `{"remote": {"enabled": true}}` (no mode) from
        // fail-closed to binding 0.0.0.0.
        for config in [
            RemoteConfig::default(),
            RemoteConfig::from_settings_value(&serde_json::json!({
                "version": 3,
                "workspaces": {}
            })),
        ] {
            assert_eq!(config.listener_mode, ListenerMode::Off);
            assert!(!config.enabled);
            assert!(!config.is_loopback_ready());
        }
    }

    #[test]
    fn unknown_listener_mode_fails_closed() {
        let raw = serde_json::json!({
            "remote": { "enabled": true, "listener_mode": "overlay" }
        });
        let config = RemoteConfig::from_settings_value(&raw);
        assert!(!config.is_loopback_ready());
        assert_eq!(config.listener_mode, ListenerMode::Off);
    }

    #[test]
    fn local_network_mode_is_ready_with_token() {
        let raw = serde_json::json!({
            "remote": {
                "enabled": true,
                "listener_mode": "local_network",
                "access_token": "secret"
            }
        });
        let config = RemoteConfig::from_settings_value(&raw);
        assert!(config.is_loopback_ready());
        assert_eq!(config.listener_mode, ListenerMode::LocalNetwork);
        assert_eq!(
            config.bind_address(),
            std::net::IpAddr::V4(std::net::Ipv4Addr::UNSPECIFIED)
        );
    }

    #[test]
    fn ensure_identity_fills_missing_fields_once() {
        let mut config = RemoteConfig::default();
        assert!(config.ensure_identity());
        let host_id = config.host_id.clone().unwrap_or_default();
        let token = config.access_token.clone().unwrap_or_default();
        assert!(host_id.starts_with("shardlane-host-"));
        assert_eq!(token.len(), 64);
        assert!(!config.ensure_identity(), "identity must be stable");
        assert_eq!(config.host_id, Some(host_id));
    }

    #[test]
    fn enabled_without_token_is_not_ready() {
        let config = RemoteConfig {
            enabled: true,
            listener_mode: ListenerMode::Loopback,
            ..RemoteConfig::default()
        };
        assert!(!config.is_loopback_ready(), "token is mandatory");
    }

    #[test]
    fn port_defaults_and_legacy_zero_normalize_to_default() {
        // Product defaults: both RemoteConfig::default() and a serde-missing
        // field yield 8757 directly; an explicit 0 in legacy files is
        // normalized at the loading layer (the server binding layer keeps
        // the 0=ephemeral semantics, reserved for explicit test
        // construction, and never goes through this function).
        assert_eq!(RemoteConfig::default().port, DEFAULT_REMOTE_PORT);

        let raw = serde_json::json!({
            "remote": {
                "enabled": true,
                "listener_mode": "local_network",
                "access_token": "secret"
            }
        });
        assert_eq!(
            RemoteConfig::from_settings_value(&raw).port,
            DEFAULT_REMOTE_PORT
        );

        let legacy_zero = serde_json::json!({
            "remote": {
                "enabled": true,
                "listener_mode": "local_network",
                "port": 0,
                "access_token": "secret"
            }
        });
        assert_eq!(
            RemoteConfig::from_settings_value(&legacy_zero).port,
            DEFAULT_REMOTE_PORT
        );

        let configured = serde_json::json!({
            "remote": {
                "enabled": true,
                "listener_mode": "local_network",
                "port": 9100,
                "access_token": "secret"
            }
        });
        assert_eq!(RemoteConfig::from_settings_value(&configured).port, 9100);
    }
}

fn fresh_access_token() -> String {
    let a = uuid::Uuid::new_v4().simple();
    let b = uuid::Uuid::new_v4().simple();
    format!("{a}{b}")
}

#[cfg(test)]
mod rotate_tests {
    use super::*;

    #[test]
    fn rotate_keeps_host_id_and_replaces_token() {
        let mut config = RemoteConfig::default();
        config.ensure_identity();
        let host_id = config.host_id.clone();
        let old_token = config.access_token.clone().unwrap_or_default();
        let new_token = config.rotate_access_token();
        assert_eq!(config.host_id, host_id);
        assert_ne!(new_token, old_token);
        assert_eq!(config.access_token.as_deref(), Some(new_token.as_str()));
        assert_eq!(new_token.len(), 64);
    }

    #[test]
    fn web_url_round_trips_and_defaults_to_none() {
        let raw = serde_json::json!({
            "remote": {
                "enabled": true,
                "listener_mode": "loopback",
                "port": 8757,
                "web_url": "https://shardlane.dev.local"
            }
        });
        let config = RemoteConfig::from_settings_value(&raw);
        assert_eq!(
            config.web_url.as_deref(),
            Some("https://shardlane.dev.local")
        );
        let back = serde_json::to_value(&config).unwrap_or_default();
        assert_eq!(back["web_url"], "https://shardlane.dev.local");

        let bare = RemoteConfig::from_settings_value(&serde_json::json!({}));
        assert_eq!(bare.web_url, None);
        let serialized = serde_json::to_value(&bare).unwrap_or_default();
        assert!(
            serialized.get("web_url").is_none(),
            "unset web_url must not serialize"
        );
    }
}
